### ISSUE TITLE
[BUG]:Devproxy is not returning the response

### ISSUE THREAD

**Issue by DivyaTheetlaPG** [dotnet/dev-proxy#899]
### Description

![config file](https://github.com/user-attachments/assets/39041778-c07a-424a-a4f5-4d9fd5d18b82)
![Uploading config file.png…]()
uploaded config file

### Expected behaviour

 req    GET https://jsonplaceholder.typicode.com/posts
 api   Passed through

### Actual behaviour

not recording any response

### Steps to reproduce

to check why the response is not getting recorded

### Dev Proxy Version

0.21.0

### Operating system (environment)

Windows

### Shell

cmd

### Configuration file

![config file](https://github.com/user-attachments/assets/feb7abef-9d47-4e4e-b659-7b3e616fab06)

```[tasklist]
### Tasks
```

**Comment by DivyaTheetlaPG** [comment]
![powershell request](https://github.com/user-attachments/assets/4d5149e3-a592-44d3-9e56-0ab63d9bef5b)
![postman req](https://github.com/user-attachments/assets/8207eb89-0554-4759-94df-b30a6f89bcc8)
![cmd report](https://github.com/user-attachments/assets/943e2dcc-6a32-48fb-a912-f7fab0479e10)
attaching the calling the API from powershell and postman and the cmd

**Comment by waldekmastykarz** [comment]
Thanks for reporting the issue and sorry for the trouble. Could it be that your PowerShell sessions hasn't automatically picked up your system proxy settings? Could you please try running this to see if it makes a difference:

```powershell
Invoke-WebRequest -Uri https://jsonplaceholder.typicode.com/posts -Proxy http://127.0.0.1:8000
```

**Comment by DivyaTheetlaPG** [comment]
Thanks for the quick reply, and it is working.
